# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
annotations: {}

image:
  repository: networkstatic/iperf3
  tag: latest
  pullPolicy: Always
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: NodePort
  nodePort: 30201

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
